models/contact.py
from utils.db import db


class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(100))
    email = db.Column(db.String(100))
    phone = db.Column(db.String(100))

    def __init__(self, fullname, email, phone):
        self.fullname = fullname
        self.email = email
        self.phone = phone

app.py
from flask import Flask
from routes.contacts import contacts
from utils.db import db

app = Flask(__name__)
app.secret_key = "secret_key"
app.config["SQLALCHEMY_DATABASE_URI"] = "URL DE CONEXIÓON A LA BASE DE DATOS"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

db.init_app(app)

app.register_blueprint(contacts)

routes/contacts.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.contact import Contact
from utils.db import db

contacts = Blueprint('contacts', __name__)


@contacts.route('/')
def home():
    contacts = Contact.query.all()
    return render_template("index.html", contacts=contacts)


@contacts.route('/about')
def about():
    return render_template("about.html")

@contacts.route('/new', methods=['POST'])
def new():
    fullname = request.form['fullname']
    email = request.form['email']
    phone = request.form['phone']

    new_contact = Contact(fullname, email, phone)
    try:
        if fullname!="" or email!="" and phone!="":
            db.session.add(new_contact)
            db.session.commit()
            flash('Contact created successfully!')
            return redirect(url_for('contacts.home'))
        else:
            flash('Los campos no pueden estar vacíos')
            return redirect(url_for('contacts.home'))
    except:
        return redirect(url_for('contacts.home'))


@contacts.route("/update/<id>", methods=["POST", "GET"])
def update(id):
    contact = Contact.query.get(id)
    if request.method == "POST":
        try:
            contact.fullname = request.form["fullname"]
            contact.email = request.form["email"]
            contact.phone = request.form["phone"]
            db.session.commit()
            flash("Contact updated")
            return redirect(url_for('contacts.home'))
        except:
            return render_template("ErrorSaving.html")
    return render_template("update.html", contact=contact)


@contacts.route("/delete/<id>")
def delete(id):
    try:
        contact = Contact.query.get(id)
        db.session.delete(contact)
        db.session.commit()
        flash("Contact deleted")
        return redirect(url_for('contacts.home'))
    except:
        return render_template("ErrorDeleting.html")

templates/ErrorDeleting.html
{%extends 'layout.html'%} 
{%block content%}
<main>
  <section>
    <p class="alert alert-danger" role="alert">Error trying to delete</p>
  </section>
</main>
{%endblock%}

templates/ErrorSaving.html
{%extends 'layout.html'%}
{%block content%}
<main>
  <section>
    <p class="alert alert-danger" role="alert">Error al intentar agendar.</p>
  </section>
</main>
{%endblock%}

templates/about.html
{%extends 'layout.html'%}
{%block content%}
<main>
  <section>
    <h1>Acerca del proyecto</h1>
    <p>Este proyecto es un ejemplo práctico de como usar Flask y SQL para hacer un crud</p>
  </section>
</main>
{%endblock%}

templates/index.html
{% extends 'layout.html' %} 
{%block content%} 

<div class="flex flex-row">
  <div class="w-2/6">
    {%include('partials/_contactForm.html')%}
    {%include('partials/_messages.html')%}
  </div>
  <div class="flex flex-col">
    <div class="overflow-x-auto sm:mx-6 lg:mx-8">
      <div class="overflow-hidden">
        <table class="min-w-full text-left text-sm font-light">
          <thead class="border-b text-white font-medium dark:border-neutral-500 dark:bg-neutral-600">
            <tr>
              <th scope="col" class="px-6 py-4">Name</th>
              <th scope="col" class="px-6 py-4">Phone</th>
              <th scope="col" class="px-6 py-4">Email</th>
              <th scope="col" class="px-6 py-4">Update</th>
              <th scope="col" class="px-6 py-4">Delete</th>
            </tr>
          </thead>
          <tbody>
            {% for contact in contacts %}
            <tr class="border-b bg-neutral-100 dark:border-neutral-500 dark:bg-neutral-700 text-white font-semibold">
              <td class="whitespace-nowrap px-6 py-4">{{contact.fullname}}</td>
              <td class="whitespace-nowrap px-6 py-4">{{contact.phone}}</td>
              <td class="whitespace-nowrap px-6 py-4">{{contact.email}}</td>
              <td class="whitespace-nowrap px-6 py-4">
                <a
                  class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                  href="{{ url_for('contacts.update',id=contact.id) }}"
                  >Update</a
                >
              </td>
              <td>
                <a
                  class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                  href="{{ url_for('contacts.delete', id=contact.id) }}"
                  >Delete</a
                >
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{%endblock%}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Flask SQLAlchemy Crud</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-slate-800">
  {% include('partials/_navbar.html') %}
  <div class="flex flex-col">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

templates/partials/_contactForm.html
<div class="w-full max-w-md">
  <form method="post" action="/new" class="bg-slate-500 shadow-lg rounded mx-6 px-8 pt-6 pb-8 mb-4">
      <div class="mb-4">
        <label class="block text-slate-700 text-sm font-bold mb-2" for="fullname">Write your fullname:</label>
        <input type="text" name="fullname" placeholder="fullname" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"/>
      </div>
      <div class="mb-3">
        <label class="block text-slate-700 text-sm font-bold mb-2" for="phone">Write your phone:</label>
        <input type="number" name="phone" placeholder="phone" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" required/>
      </div>
      <div class="mb-3">
        <label class="block text-slate-700 text-sm font-bold mb-2" for="email">Write your email:</label>
        <input type="email" name="email" placeholder="email" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" required/>
      </div>
    <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">Save</button>
  </form>
</div>

templates/partials/_messages.html
{% with messages =get_flashed_messages() %} 
  {% if messages %} 
    {%for message in messages%}
    <div class="bg-indigo-900 text-center py-4 lg:px-4 rounded">
      <div class="p-2 bg-indigo-800 items-center text-indigo-100 leading-none lg:rounded-full flex lg:inline-flex" role="alert">
        <span class="flex rounded-full bg-indigo-500 uppercase px-2 py-1 text-xs font-bold mr-3">New message!</span>
        <span class="font-semibold mr-2 text-left flex-auto">{{message}}</span>
        <svg class="fill-current opacity-75 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M12.95 10.707l.707-.707L8 4.343 6.586 5.757 10.828 10l-4.242 4.243L8 15.657l4.95-4.95z"/></svg>
      </div>
    </div>
    {%endfor%} 
  {% endif %} 
{% endwith %}

templates/partials/_navbar.html
<nav class="bg-green-300 px-3 py-1 mb-4">
  <div class="container">
    <a class="float-left text-white font-bold pt-2.5" href="/">Flask SQLAlchemy CRUD</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/about">About</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/update.html
{%extends 'layout.html'%}
{%block content%}
<div class="w-full max-w-md">
  <form method="post" action="/new" class="bg-slate-500 shadow-lg rounded mx-6 px-8 pt-6 pb-8 mb-4">
      <div class="mb-4">
        <label class="block text-slate-700 text-sm font-bold mb-2" for="fullname">Write your fullname:</label>
        <input type="text" name="fullname" placeholder="fullname" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" value="{{contact.fullname}}"/>
      </div>
      <div class="mb-3">
        <label class="block text-slate-700 text-sm font-bold mb-2" for="phone">Write your phone:</label>
        <input type="number" name="phone" placeholder="phone" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" value="{{contact.phone}}"/>
      </div>
      <div class="mb-3">
        <label class="block text-slate-700 text-sm font-bold mb-2" for="email">Write your email:</label>
        <input type="email" name="email" placeholder="email" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" value="{{contact.email}}"/>
      </div>
    <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full text-center" type="submit">Save</button>
  </form>
</div>

{%endblock%}